# Solar Swarm Intelligence Configuration

# System Settings
system:
  num_agents: 50
  simulation_hours: 24
  timestep_seconds: 3600  # 1 hour
  random_seed: 42

# Agent Configuration
agent:
  battery_capacity_kwh: 10.0
  initial_battery_pct: 50.0
  solar_panel_capacity_kw: 5.0
  system_loss_pct: 14.0
  
  # Consumption profiles
  consumption:
    low_user: [0.5, 1.5]  # kWh range
    medium_user: [1.5, 3.0]
    high_user: [3.0, 5.0]
    distribution: [0.3, 0.5, 0.2]  # 30% low, 50% medium, 20% high

# Neighborhood Topology
neighborhood:
  grid_size: [10, 5]  # 10x5 grid = 50 houses
  neighbor_radius: 3  # Connect to neighbors within 3 units
  topology_type: "grid"  # grid, random, small_world

# Forecasting Models
forecasting:
  lstm:
    input_size: 10
    hidden_size: 64
    num_layers: 2
    dropout: 0.2
    sequence_length: 24
    batch_size: 32
    epochs: 50
    learning_rate: 0.001
  
  prophet:
    yearly_seasonality: true
    weekly_seasonality: true
    daily_seasonality: true
    changepoint_prior_scale: 0.05

# Anomaly Detection
anomaly:
  isolation_forest:
    contamination: 0.1
    n_estimators: 100
    max_samples: 256
  
  autoencoder:
    input_dim: 10
    hidden_dims: [8, 4]
    epochs: 100
    threshold_percentile: 95

# Reinforcement Learning
rl:
  algorithm: "PPO"
  policy: "MlpPolicy"
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  total_timesteps: 100000
  
  # Reward function weights
  rewards:
    solar_storage: 2.0
    energy_sharing: 3.0
    grid_export: 1.0
    grid_import_penalty: -5.0
    low_battery_penalty: -10.0

# Simulation Physics
physics:
  # Solar irradiance (W/m²)
  peak_irradiance: 1000
  panel_efficiency: 0.18
  temperature_coefficient: -0.004  # per °C
  
  # Weather effects
  cloud_impact:
    clear: 1.0
    partly_cloudy: 0.7
    cloudy: 0.3
    overcast: 0.1

# Economic Parameters
economics:
  grid_buy_price: 0.15  # TND/kWh
  grid_sell_price: 0.10  # TND/kWh
  peer_trade_price: 0.12  # TND/kWh
  battery_degradation_cost: 0.02  # TND/cycle

# Environmental
environmental:
  grid_co2_intensity: 0.5  # kg CO2/kWh (Tunisia)
  tree_co2_absorption: 21  # kg CO2/year/tree

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
  websocket_update_interval: 5  # seconds

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/solar_swarm.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Data Paths
paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_synthetic: "data/processed/synthetic"
  models: "models"
  results: "results"
  logs: "logs"

# Performance Targets
targets:
  solar_utilization_pct: 87.0
  forecast_mape_max: 15.0
  cost_savings_pct: 35.0
  simulation_speed_max_seconds: 10.0
